# Generated by Django 4.1.3 on 2023-01-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goppobagisgecomapp', '0003_products_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
