# Generated by Django 4.1.3 on 2023-01-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goppobagisgecomapp', '0006_remove_orders_customer_orders_cityorvillage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Discount',
            field=models.FloatField(default=0.0, verbose_name='gfgfgf'),
        ),
    ]
